version: '3.8'
services:
  frontend:
    build: ./client
    ports:
      - "3312:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL} # Adjust if necessary to connect frontend to backend
    depends_on:
      - backend

  backend:
    build: ./api
    ports:
      - "3313:5000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - PORT=${PORT}
    depends_on:
      - mongodb
    

  mongodb:
    image: mongo:5.0
    volumes:
      - mongodb_data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=root


volumes:
  mongodb_data:

